server.port=8099
bootstrap_server=localhost:29092
spring.cloud.stream.kafka.binder.brokers=localhost:29092
kafka.streams.host.info=localhost:8099
kafka.streams.state.dir=/tmp/kafka-streams/async-process-local
spring.config.import=optional:configserver:http://localhost:8888
management.endpoints.web.exposure.include=health,metrics
auth.disabled=true
spring.kafka.bootstrap-servers=localhost:29092
