def updateCommitStatus(repositoryName, status, description, accessToken, gitCommit, buildUrl, contextBuild) {
  sh "./pipelines/run-tests/utils/build-update.sh ${repositoryName} ${status} \"${description}\" ${accessToken} ${gitCommit} ${buildUrl} \"${contextBuild}\""
}

pipeline {
    environment { // MARK: Environment variables
        CONTEXT_NAME        = 'etendo'
        BBDD_SID            = 'etendo'
        BBDD_PORT           = '5432'
        BBDD_SYSTEMUSER     = 'postgres'
        BBDD_SYSTEMPASS     = 'syspass'
        BBDD_USER           = 'tad'
        BBDD_PASSWORD       = 'tad'
        NEXUS_USER          = credentials('nexus-admin-user')
        NEXUS_PASSWORD      = credentials('nexus-admin-passwd')
        GITHUB_USER         = 'etendobot'
        GITHUB_TOKEN        = credentials('github-read-package-token')
        JAVA_HOME           = '/usr/lib/jvm/java-17-openjdk-amd64'
        ACCESS_TOKEN        = credentials('access_token_github')
        EMAIL_ADDRESS       = credentials('email_builds')
        RX_REPO_URL         = 'https://github.com/etendosoftware/etendo_rx'
        RX_DIR              = 'etendo_rx'

        MODULE_RX_URL                  = 'git@github.com:etendosoftware/com.etendoerp.etendorx.git'
        PET_CLINIC_CLASSIC_MODULE_URL  = 'https://github.com/etendosoftware/com.etendoerp.integration.petclinic.git'
        PET_CLINIC_RX_MODULE_URL       = 'https://github.com/etendosoftware/com.etendorx.integration.petclinic.git'

        COMMIT_AUTHOR_NAME  = sh(returnStdout: true, script: "git log -1 --pretty=format:'%an'").trim()
        COMMIT_AUTHOR_EMAIL = sh(returnStdout: true, script: "git log -1 --pretty=format:'%ae'").trim()

        BUILD_CLASSIC       = true
        TOMCAT_URL          = "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.98/bin/apache-tomcat-9.0.98.tar.gz"

        SUCCESS             = 'SUCCESS'
        FAILED              = 'FAILED'
        ABORTED             = 'ABORTED'
        UNSTABLE            = 'UNSTABLE'

        COMMIT_INPROGRESS_STATUS = "pending"
        COMMIT_SUCCESS_STATUS    = "success"
        COMMIT_FAILED_STATUS     = "failure"

        CONTEXT_BUILD = "RX Core Tests"
    }

    agent { // MARK: Agent
        kubernetes {
            inheritFrom 'jenkins-node-rx'
            defaultContainer 'jnlp'
            yamlFile 'pipelines/run-tests/Agent.yaml'
        }
    }
    stages { // MARK: Stages
        stage('Check Pipeline Skip Condition') { // MARK: Check Pipeline Skip Condition
            steps {
                script {
                    try {
                        env.DESCRIPTION = "Checking if pipeline should be skipped"
                        updateCommitStatus(RX_DIR, COMMIT_INPROGRESS_STATUS, env.DESCRIPTION, ACCESS_TOKEN, GIT_COMMIT, BUILD_URL, CONTEXT_BUILD)
                        echo "--------------- ${env.DESCRIPTION} ---------------"
                        def changedFiles = sh(
                            script: "git diff --name-only HEAD~1 HEAD",
                            returnStdout: true
                        ).trim()
                            
                        echo "Files changed in last commit: ${changedFiles}"
                        
                        // Check if only JenkinsFileTestCompile was changed
                        def filesList = changedFiles.split('\n')
                        def onlyJenkinsfile = filesList.every { it.startsWith("pipelines/publish-snapshots/") } && filesList.size() > 0

                        if (onlyJenkinsfile) {
                            echo "⏭️ Only pipelines/publish-snapshots/ related files were changed. Skipping pipeline execution."
                            env.DESCRIPTION = "Pipeline Skipped - Only pipelines/publish-snapshots/ files changed"
                            updateCommitStatus(RX_DIR, COMMIT_SUCCESS_STATUS, env.DESCRIPTION, ACCESS_TOKEN, GIT_COMMIT, BUILD_URL, CONTEXT_BUILD)

                            echo "✅ Pipeline execution aborted successfully. Commit marked as success."
                            currentBuild.result = ABORTED
                            return
                        } else {
                            echo "✅ Pipeline will continue - Changes detected in other files or multiple files changed."
                            updateCommitStatus(RX_DIR, COMMIT_INPROGRESS_STATUS, env.DESCRIPTION, ACCESS_TOKEN, GIT_COMMIT, BUILD_URL, CONTEXT_BUILD)
                            currentBuild.result = SUCCESS
                        }
                    } catch (Exception e) {
                        echo "❌ Error in pipeline skip condition check: ${e.getMessage()}"            
                        env.DESCRIPTION = "Pipeline Check Failed"
                        currentBuild.result = FAILED
                        error("Failed to check pipeline skip condition: ${e.getMessage()}")
                    }
                }
            }
        }
        stage ('Clone and Setup RX Repo') { // MARK: Clone RX Repo
            when {
                expression {
                    currentBuild.result == SUCCESS
                }
            }
            steps {
                container('compiler') {
                    script {
                        try {
                            env.DESCRIPTION = "Clone and Setup RX"
                            updateCommitStatus(RX_DIR, COMMIT_INPROGRESS_STATUS, env.DESCRIPTION, ACCESS_TOKEN, GIT_COMMIT, BUILD_URL, CONTEXT_BUILD)
                            echo "---------------------- ${env.DESCRIPTION} ----------------------"
                            echo "---------------------- Setting up Environment Variables ----------------------"
                            env.JACOCO_REPORT_EXISTS = false // Flag to track if any JaCoCo report is generated
                            env.TEST_STATUS = SUCCESS // Overall test status
                            env.RX_STATUS = SUCCESS // Overall RX build status
                            env.FAILED_SUITES = "" // List to collect failed test suites

                            echo "---------------------- Clonning RX Repo ----------------------"
                            sh """
                            printenv
                            git clone ${RX_REPO_URL}
                            """

                            echo "--------------- Checking out to Commit Hash ---------------"
                            def commitExists = sh(script: """
                            cd ${RX_DIR}
                            git cat-file -t ${GIT_COMMIT}
                            """, returnStatus: true) == 0

                            if (!commitExists) {
                                currentBuild.result = ABORTED
                                env.COMMIT_INFO = "Commit hash ${GIT_COMMIT} does not exist in the repository."
                                echo "Commit hash ${GIT_COMMIT} does not exist in the repository."
                                return
                            }

                            echo "---------------------- Setup RX Repo ----------------------"
                            sh """
                            cd ${RX_DIR}
                            git checkout ${GIT_COMMIT}
                            cp gradle.properties.template gradle.properties
                            sed -i 's/^githubUser=.*/githubUser=${GITHUB_USER}/' gradle.properties
                            sed -i 's/^githubToken=.*/githubToken=${GITHUB_TOKEN}/' gradle.properties
                            sed -i 's/^grpc.enabled=.*/grpc.enabled=true/' gradle.properties
                            sed -i 's/^data-rest.enabled=.*/data-rest.enabled=true/' gradle.properties
                            mkdir -p modules
                            ./gradlew setup
                            """
                            
                            env.COMMIT_INFO = "<p>• Commit: ${RX_REPO_URL}/commit/${GIT_COMMIT}<br>• Author: ${COMMIT_AUTHOR_NAME} (${COMMIT_AUTHOR_EMAIL})</p>"
                            echo "---------------------- Commit Info ----------------------"
                            echo "${COMMIT_INFO}"

                            currentBuild.result = SUCCESS
                            echo "---------------------- Clone and Setup RX Repo Successful ----------------------"
                        } catch (Exception e) {
                            echo 'Exception occurred: ' + e.toString()
                            echo "---------------------- Clone and Setup RX Repo Failed ----------------------"
                            currentBuild.result = FAILED
                            error('Clone and Setup RX Repo Failed')
                            env.RX_STATUS = FAILED
                        }
                    }
                }
            }
        }
        stage ('Build Environment Etendo Classic') { // MARK: Build Environment Etendo Classic
            when {
                expression {
                    env.BUILD_CLASSIC == "true" && currentBuild.result == SUCCESS
                }
            }
            steps {
                container('compiler') {
                    script {
                        try {
                            env.DESCRIPTION = "Building Etendo Classic Environment"
                            updateCommitStatus(RX_DIR, COMMIT_INPROGRESS_STATUS, env.DESCRIPTION, ACCESS_TOKEN, GIT_COMMIT, BUILD_URL, CONTEXT_BUILD)
                            echo "---------------------- ${env.DESCRIPTION} ----------------------"

                            echo "---------------- Stack Configuration ----------------"
                            sh "wget -O apache-tomcat.tar.gz ${TOMCAT_URL}"
                            sh "tar -xvf apache-tomcat.tar.gz -C ${WORKSPACE}"

                            env.TOMCAT_FOLDER = sh(script: "basename ${TOMCAT_URL} .tar.gz", returnStdout: true).trim()
                            env.CATALINA_HOME = "${WORKSPACE}/${TOMCAT_FOLDER}"
                            env.CATALINA_BASE = "${WORKSPACE}/${TOMCAT_FOLDER}"

                            withCredentials([sshUserPrivateKey(credentialsId: 'my-credentials', keyFileVariable: 'keyfile')]) {
                                echo "---------------------- Starting Classic Environment ----------------------"
                                sh "GIT_SSH_COMMAND=\"ssh -i ${keyfile} -o \"UserKnownHostsFile=/dev/null\" -o \"StrictHostKeyChecking=no\"\" git clone --branch main git@github.com:etendosoftware/etendo_core.git"
                                dir("etendo_core") {
                                    sh """
                                    echo "
                                    context.name=${CONTEXT_NAME}
                                    bbdd.sid=${BBDD_SID}
                                    bbdd.port=${BBDD_PORT}
                                    bbdd.systemUser=${BBDD_SYSTEMUSER}
                                    bbdd.systemPassword=${BBDD_SYSTEMPASS}
                                    bbdd.user=${BBDD_USER}
                                    bbdd.password=${BBDD_PASSWORD}
                                    nexusUser=${NEXUS_USER}
                                    nexusPassword=${NEXUS_PASSWORD}
                                    githubUser=${GITHUB_USER}
                                    githubToken=${GITHUB_TOKEN}
                                    allow.root=true
                                    org.gradle.jvmargs=-Dfile.encoding=UTF-8" > gradle.properties
                                    """
                                    sh "./gradlew prepareConfig --stacktrace"
                                    sh "./gradlew setup --stacktrace"
                                    sh "./gradlew expandModules --stacktrace"

                                    sh """
                                    cd modules
                                    GIT_SSH_COMMAND=\"ssh -i ${keyfile} -o \"UserKnownHostsFile=/dev/null\" -o \"StrictHostKeyChecking=no\"\" git clone --branch main ${MODULE_RX_URL}
                                    git clone --branch main ${PET_CLINIC_CLASSIC_MODULE_URL}
                                    """
                                    
                                    sh "./gradlew install --stacktrace"
                                    sh "./gradlew smartbuild --stacktrace"
                                    currentBuild.result = SUCCESS
                                    echo "---------------------- Classic Environment Successful ----------------------"
                                }
                            }

                            echo "---------------------- Inserting Configs ----------------------"
                            withEnv(["PGPASSWORD=${env.BBDD_PASSWORD}"]) {
                                sh """
                                    psql -h localhost -U ${BBDD_USER} -d ${BBDD_SID} -f ./pipelines/run-tests/utils/sql/insert_test_configurations.sql
                                """
                            }
							sh "${WORKSPACE}/${TOMCAT_FOLDER}/bin/catalina.sh start"
							sh "sleep 1m"
                            echo "--------------- Build Environment Successful ---------------"
                        } catch (Exception e) {
                            env.ERROR_MESSAGE = "Build of Classic Environment Failed"
                            echo "--------------- ${env.ERROR_MESSAGE} ---------------"
                            echo 'Exception occurred: ' + e.toString()
                            currentBuild.result = FAILED
                            error(env.ERROR_MESSAGE)
                        }
                    }
                }
            }
        }
        stage ('Build Environment Etendo RX') { // MARK: Build Environment Etendo RX
            when {
                expression {
                    currentBuild.result == SUCCESS
                }
            }
            steps {
                container('compiler') {
                    script {
                        try {
                            env.DESCRIPTION = "Building Etendo RX Environment"
                            echo "---------------------- ${env.DESCRIPTION} ----------------------"
                            updateCommitStatus(RX_DIR, COMMIT_INPROGRESS_STATUS, env.DESCRIPTION, ACCESS_TOKEN, GIT_COMMIT, BUILD_URL, CONTEXT_BUILD)

                            sh """
                            cd ${RX_DIR}
                            mkdir -p modules
                            mkdir -p modules_test
                            cd modules_test
                            git clone --branch main ${PET_CLINIC_RX_MODULE_URL}
                            cd ..
                            ./gradlew generate.entities
                            """
                            currentBuild.result = SUCCESS
                            echo "---------------------- Build of Etendo RX Successful ----------------------"
                        } catch (Exception e) {
                            env.ERROR_MESSAGE = "Build of Etendo RX Failed"
                            echo "--------------- ${env.ERROR_MESSAGE} ---------------"
                            echo 'Exception occurred: ' + e.toString()
                            currentBuild.result = FAILED
                            error(env.ERROR_MESSAGE)
                            env.RX_STATUS = FAILED
                        }
                    }
                }
            }
        }
        stage ("Run AsyncProcess Tests") { // MARK: Run AsyncProcess Tests
            when {
                expression {
                    false
                }
            }
            steps {
                script {
                    def suiteName = "com.etendorx.asyncprocess"
                    try {
                        env.DESCRIPTION = "Running ${suiteName} Tests"
                        echo "---------------------- ${env.DESCRIPTION} ----------------------"
                        updateCommitStatus(RX_DIR, COMMIT_INPROGRESS_STATUS, env.DESCRIPTION, ACCESS_TOKEN, GIT_COMMIT, BUILD_URL, CONTEXT_BUILD)
                        sh """
                        cd ${RX_DIR}
                        ./gradlew :${suiteName}:test jacocoRootReport
                        """
                        echo "---------------------- ${suiteName} Tests Successful ----------------------"
                    } catch (Exception e) {
                        env.ERROR_MESSAGE = "${suiteName} Tests Failed"
                        echo "--------------- ${env.ERROR_MESSAGE} ---------------"
                        echo 'Exception occurred: ' + e.toString()
                        currentBuild.result = UNSTABLE
                        unstable(env.ERROR_MESSAGE)
                        env.TEST_STATUS = UNSTABLE
                        def currentFailed = env.FAILED_SUITES ?: ""
                        env.FAILED_SUITES = currentFailed.isEmpty() ? "${suiteName}" : "${currentFailed}, ${suiteName}"
                    } finally {
                        publishHTML([
                            allowMissing: false,
                            alwaysLinkToLastBuild: false,
                            keepAll: true,
                            reportDir: "${RX_DIR}/modules_core/${suiteName}/build/reports/tests/test",
                            reportFiles: '*.html',
                            reportName: "${suiteName} Tests Report",
                            reportTitles: ''
                        ])
                    }
                }
            }
        }
        stage ("Run Auth Tests") { // MARK: Run Auth Tests
            when {
                expression {
                    env.RX_STATUS == SUCCESS
                }
            }
            steps {
                container("compiler") {
                    script {
                        def suiteName = "com.etendorx.auth"
                        try {
                            env.DESCRIPTION = "Running ${suiteName} Tests"
                            echo "---------------------- ${env.DESCRIPTION} ----------------------"
                            updateCommitStatus(RX_DIR, COMMIT_INPROGRESS_STATUS, env.DESCRIPTION, ACCESS_TOKEN, GIT_COMMIT, BUILD_URL, CONTEXT_BUILD)
                            echo "---------------------- Building services ----------------------"
                            dir("${RX_DIR}") {
                                sh """
                                    ./gradlew com.etendorx.configserver:build -x test
                                    ./gradlew com.etendorx.das:build -x test
                                    ./gradlew com.etendorx.entities:build -x test
                                    ./gradlew com.etendorx.auth:build -x test
                                """

                                def rxVersion = sh(
                                    script: "grep 'gradle.ext.version' settings.gradle | awk -F\"'\" '{print \$2}'",
                                    returnStdout: true
                                ).trim()

                                env.RX_VERSION = rxVersion

                                sh """
                                    cp modules_core/com.etendorx.configserver/build/libs/com.etendorx.configserver-${env.RX_VERSION}.jar /tmp/
                                    cp modules_core/com.etendorx.das/build/libs/com.etendorx.das-${env.RX_VERSION}.jar /tmp/
                                    cp modules_gen/com.etendorx.entities/build/libs/com.etendorx.entities-${env.RX_VERSION}-plain.jar /tmp/
                                    cp modules_core/com.etendorx.auth/build/libs/com.etendorx.auth-${env.RX_VERSION}.jar /tmp/

                                    echo "---------------------- Running ${suiteName} Tests ----------------------"
                                    ./gradlew ${suiteName}:test
                                    ./gradlew jacocoTestReport
                                """
                            }
                            echo "---------------------- ${suiteName} Tests Successful ----------------------"
                        } catch (Exception e) {
                            env.ERROR_MESSAGE = "${suiteName} Tests Failed"
                            echo "--------------- ${env.ERROR_MESSAGE} ---------------"
                            echo 'Exception occurred: ' + e.toString()
                            currentBuild.result = UNSTABLE
                            unstable(env.ERROR_MESSAGE)
                            env.TEST_STATUS = UNSTABLE
                            def currentFailed = env.FAILED_SUITES ?: ""
                            env.FAILED_SUITES = currentFailed.isEmpty() ? "${suiteName}" : "${currentFailed}, ${suiteName}"
                        } finally {
                            if (fileExists("${RX_DIR}/modules_core/com.etendorx.auth/build/reports/tests/test")) {
                                publishHTML([
                                    allowMissing: false,
                                    alwaysLinkToLastBuild: false,
                                    keepAll: true,
                                    reportDir: "${RX_DIR}/modules_core/${suiteName}/build/reports/tests/test",
                                    reportFiles: '*.html',
                                    reportName: "${suiteName} Tests Report",
                                    reportTitles: ''
                                ])
                            }
                        }
                    }
                }
            }
        }
        stage ("Run Das Tests") { // MARK: Run Das Tests
            when {
                expression {
                    env.RX_STATUS == SUCCESS
                }
            }
            steps {
                container("compiler") {
                    script {
                        def suiteName = "com.etendorx.das"
                        try {
                            env.DESCRIPTION = "Running ${suiteName} Tests"
                            updateCommitStatus(RX_DIR, COMMIT_INPROGRESS_STATUS, env.DESCRIPTION, ACCESS_TOKEN, GIT_COMMIT, BUILD_URL, CONTEXT_BUILD)
                            echo "---------------------- ${env.DESCRIPTION} ----------------------"

                            def tests = [
                                "com.etendorx.das.test.RepositoryTest",
                                "com.etendorx.das.test.RestCallTest",
                                "com.etendorx.das.test.DefaultFiltersTest",
                                "com.etendorx.das.test.eventhandlertest.test.AnnotationTests",
                                "com.etendorx.das.unit.BindedRestControllerTest",
                                "com.etendorx.das.unit.JsonPathEntityRetrieverDefaultTest",
                                "com.etendorx.das.unit.MappingUtilsImplTest",
                                "com.etendorx.das.test.DisableEnableTriggersTest",
                                "com.etendorx.das.test.FieldMappingRestCallTest",
                                "com.etendorx.das.integration.PropertyMetadataTest",
                                "com.etendorx.das.unit.BaseDTORepositoryDefaultTests",
                                "com.etendorx.das.unit.JsonPathConverterBaseTests",
                                "com.etendorx.entities.mapper.lib.JsonPathEntityRetrieverBaseTests"
                            ]

                            int counter = 1

                            dir(RX_DIR) {
                                tests.each { test ->
                                    sh "./gradlew :${suiteName}:test --info --tests ${test} jacocoTestReport"
                                    sh "mv modules_core/${suiteName}/build/jacoco/test.exec modules_core/${suiteName}/build/jacoco/test${counter}.exec"
                                    counter++
                                }
                            }
                            echo "---------------------- ${suiteName} Tests Successful ----------------------"
                        } catch (Exception e) {
                            env.ERROR_MESSAGE = "${suiteName} Tests Failed"
                            echo "--------------- ${env.ERROR_MESSAGE} ---------------"
                            echo 'Exception occurred: ' + e.toString()
                            currentBuild.result = UNSTABLE
                            unstable(env.ERROR_MESSAGE)
                            env.TEST_STATUS = UNSTABLE
                            def currentFailed = env.FAILED_SUITES ?: ""
                            env.FAILED_SUITES = currentFailed.isEmpty() ? "${suiteName}" : "${currentFailed}, ${suiteName}"
                        } finally {
                            if (fileExists("${RX_DIR}/modules_core/${suiteName}/build/reports/tests/test")) {
                                publishHTML([
                                    allowMissing: false,
                                    alwaysLinkToLastBuild: false,
                                    keepAll: true,
                                    reportDir: "${RX_DIR}/modules_core/${suiteName}/build/reports/tests/test",
                                    reportFiles: '*.html',
                                    reportName: "${suiteName} Tests Report",
                                    reportTitles: ''
                                ])
                            }
                        }
                    }
                }
            }
        }
        stage ("Run Integration Pet Clinic (RX) Tests") { // MARK: Run Integration Pet Clinic Tests
            when {
                expression {
                    env.RX_STATUS == SUCCESS
                }
            }
            steps {
                container("compiler") {
                    script {
                        def suiteName = "com.etendorx.integration.petclinic"
                        try {
                            env.DESCRIPTION = "Running ${suiteName} Tests"
                            updateCommitStatus(RX_DIR, COMMIT_INPROGRESS_STATUS, env.DESCRIPTION, ACCESS_TOKEN, GIT_COMMIT, BUILD_URL, CONTEXT_BUILD)
                            echo "---------------------- ${env.DESCRIPTION} ----------------------"
                            dir(RX_DIR) {
                                sh "./gradlew :${suiteName}:test --info jacocoTestReport"
                            }

                            echo "---------------------- ${suiteName} Tests Successful ----------------------"
                        } catch (Exception e) {
                            env.ERROR_MESSAGE = "${suiteName} Tests Failed"
                            echo "--------------- ${env.ERROR_MESSAGE} ---------------"
                            echo 'Exception occurred: ' + e.toString()
                            currentBuild.result = UNSTABLE
                            unstable(env.ERROR_MESSAGE)
                            env.TEST_STATUS = UNSTABLE
                            def currentFailed = env.FAILED_SUITES ?: ""
                            env.FAILED_SUITES = currentFailed.isEmpty() ? "${suiteName}" : "${currentFailed}, ${suiteName}"
                        } finally {
                            if (fileExists("${RX_DIR}/modules_core/${suiteName}/build/reports/tests/test")) {
                                publishHTML([
                                    allowMissing: false,
                                    alwaysLinkToLastBuild: false,
                                    keepAll: true,
                                    reportDir: "${RX_DIR}/modules_core/${suiteName}/build/reports/tests/test",
                                    reportFiles: '*.html',
                                    reportName: "${suiteName} Tests Report",
                                    reportTitles: ''
                                ])
                            }
                        }
                    }
                }
            }
        }
        stage ("Run Edge Tests") { // MARK: Run Edge Tests
            when {
                expression {
                    env.RX_STATUS == SUCCESS
                }
            }
            steps {
                container("compiler") {
                    script {
                        def suiteName = "com.etendorx.edge"
                        try {
                            env.DESCRIPTION = "Running ${suiteName} Tests"
                            updateCommitStatus(RX_DIR, COMMIT_INPROGRESS_STATUS, env.DESCRIPTION, ACCESS_TOKEN, GIT_COMMIT, BUILD_URL, CONTEXT_BUILD)
                            echo "---------------------- ${env.DESCRIPTION} ----------------------"

                            sh """
                            cd ${RX_DIR}
                            ./gradlew :${suiteName}:test jacocoTestReport
                            """
                            echo "---------------------- ${suiteName} Tests Successful ----------------------"
                        } catch (Exception e) {
                            env.ERROR_MESSAGE = "${suiteName} Tests Failed"
                            echo "--------------- ${env.ERROR_MESSAGE} ---------------"
                            echo 'Exception occurred: ' + e.toString()
                            currentBuild.result = UNSTABLE
                            unstable(env.ERROR_MESSAGE)
                            env.TEST_STATUS = UNSTABLE
                            def currentFailed = env.FAILED_SUITES ?: ""
                            env.FAILED_SUITES = currentFailed.isEmpty() ? "${suiteName}" : "${currentFailed}, ${suiteName}"
                        } finally {
                            if (fileExists("${RX_DIR}/modules_core/${suiteName}/build/reports/tests/test")) {
                                publishHTML([
                                    allowMissing: false,
                                    alwaysLinkToLastBuild: false,
                                    keepAll: true,
                                    reportDir: "${RX_DIR}/modules_core/${suiteName}/build/reports/tests/test",
                                    reportFiles: '*.html',
                                    reportName: "${suiteName} Tests Report",
                                    reportTitles: ''
                                ])
                            }
                        }
                    }
                }
            }
        }
        stage ("Run Event Handler Tests") { // MARK: Run Event Handler Tests
            when {
                expression {
                    env.RX_STATUS == SUCCESS
                }
            }
            steps {
                container("compiler") {
                    script {
                        def suiteName = "com.etendorx.test.eventhandler"
                        try {
                            env.DESCRIPTION = "Running ${suiteName}"
                            updateCommitStatus(RX_DIR, COMMIT_INPROGRESS_STATUS, env.DESCRIPTION, ACCESS_TOKEN, GIT_COMMIT, BUILD_URL, CONTEXT_BUILD)
                            echo "---------------------- ${env.DESCRIPTION} ----------------------"

                            sh """
                            cd ${RX_DIR}
                            ./gradlew :${suiteName}:test jacocoTestReport
                            """
                            echo "---------------------- ${suiteName} Successful ----------------------"
                        } catch (Exception e) {
                            env.ERROR_MESSAGE = "${suiteName} Failed"
                            echo "--------------- ${env.ERROR_MESSAGE} ---------------"
                            echo 'Exception occurred: ' + e.toString()
                            currentBuild.result = UNSTABLE
                            unstable(env.ERROR_MESSAGE)
                            env.TEST_STATUS = UNSTABLE
                            def currentFailed = env.FAILED_SUITES ?: ""
                            env.FAILED_SUITES = currentFailed.isEmpty() ? "${suiteName}" : "${currentFailed}, ${suiteName}"
                        } finally {
                            if (fileExists("${RX_DIR}/modules_test/${suiteName}/build/reports/tests/test")) {
                                publishHTML([
                                    allowMissing: false,
                                    alwaysLinkToLastBuild: false,
                                    keepAll: true,
                                    reportDir: "${RX_DIR}/modules_test/${suiteName}/build/reports/tests/test",
                                    reportFiles: '*.html',
                                    reportName: "${suiteName} Tests Report",
                                    reportTitles: ''
                                ])
                            }
                        }
                    }
                }
            }
        }
        stage('Generate Coverage Report') { // MARK: Generate Coverage Report
            when {
                expression {
                    env.RX_STATUS == SUCCESS && env.TEST_STATUS == SUCCESS
                }
            }
            steps {
                container("compiler") {
                    script {
                        dir(RX_DIR) {
                            env.DESCRIPTION = "Generating Coverage Report"
                            updateCommitStatus(RX_DIR, COMMIT_INPROGRESS_STATUS, env.DESCRIPTION, ACCESS_TOKEN, GIT_COMMIT, BUILD_URL, CONTEXT_BUILD)
                            echo "---------------------- ${env.DESCRIPTION} ----------------------"

                            echo "---------------------- Run jacocoRootReport ----------------------"
                            sh "./gradlew jacocoRootReport"

                            env.JACOCO_REPORT = "build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml"

                            if (fileExists("${JACOCO_REPORT}")) {
                                echo "---------------------- Jacoco Report Found ----------------------"
                                env.JACOCO_REPORT_EXISTS = true
                            }
                        }
                    }
                }
            }
        }

        stage('Run SonarQube Analysis') { // MARK: Run SonarQube Analysis
            when {
                expression {
                    env.RX_STATUS == SUCCESS && env.TEST_STATUS == SUCCESS && env.JACOCO_REPORT_EXISTS
                }
            }
            steps {
                container('compiler') {
                    script {
                        try {
                            env.DESCRIPTION = "Running SonarQube Analysis"
                            updateCommitStatus(RX_DIR, COMMIT_INPROGRESS_STATUS, env.DESCRIPTION, ACCESS_TOKEN, GIT_COMMIT, BUILD_URL, CONTEXT_BUILD)
                            echo "---------------------- ${env.DESCRIPTION} ----------------------"

                            echo "---------------------- Installing SonarQube Scanner ----------------------"
                            sh """
                            apt-get update && apt-get install -y wget unzip
                            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_VERSION}-linux.zip
                            unzip sonar-scanner-cli-${SONAR_VERSION}-linux.zip
                            """
                            env.PATH = "${env.PATH}:${WORKSPACE}/sonar-scanner-${SONAR_VERSION}-linux/bin"
                            dir(RX_DIR) {
                                def sonarSources = "./libs,./modules_core" 
                                def sonarProjectKey = sh(script: "grep 'sonar.projectKey' sonar-project.properties | cut -d '=' -f2", returnStdout: true).trim()
                                env.PROJECT_KEY = sonarProjectKey
                                echo "SonarQube Project Key: ${env.PROJECT_KEY}"

                                echo "---------------------- Running SonarQube ----------------------"
                                sh """
                                ${WORKSPACE}/sonar-scanner-${SONAR_VERSION}-linux/bin/sonar-scanner -X \
                                    -Dsonar.projectKey=${env.PROJECT_KEY} \
                                    -Dsonar.sources=${sonarSources} \
                                    -Dsonar.host.url=${SONAR_SERVER} \
                                    -Dsonar.login=${SONAR_TOKEN} \
                                    -Dsonar.branch.name=${GIT_BRANCH} \
                                    -Dsonar.projectVersion=${GIT_COMMIT} \
                                    -Dsonar.java.coveragePlugin=jacoco \
                                    -Dsonar.scm.revision=${GIT_COMMIT} \
                                    -Dsonar.coverage.jacoco.xmlReportPaths=${JACOCO_REPORT}
                                """
                                
                                echo "---------------------- Getting SonarQube Report URL ----------------------"
                                def branchName = URLEncoder.encode(GIT_BRANCH, 'UTF-8')
                                def projectUrl = "${SONAR_SERVER}/dashboard?id=${env.PROJECT_KEY}&branch=${branchName}"
                                env.PROJECT_URL = "${projectUrl}"
                                echo "SonarQube Project URL: ${env.PROJECT_URL}"
                                echo "---------------------- SonarQube Analysis Successful ----------------------"
                            }
                        } catch (Exception e) {
                            env.ERROR_MESSAGE = "SonarQube Analysis Failed"
                            echo "--------------- ${env.ERROR_MESSAGE} ---------------"
                            echo 'Exception occurred: ' + e.toString()
                            currentBuild.result = FAILED
                            error(env.ERROR_MESSAGE)
                        }
                    }
                }
            }
        }
        stage('Compare Coverage Results') { // MARK: - Compare Coverage Results
            when {
                expression {
                    currentBuild.result == SUCCESS && env.JACOCO_REPORT_EXISTS && !(env.GIT_BRANCH == 'main' || env.GIT_BRANCH.startsWith("release/"))
                }
            }
            steps {
                script {
                    try {
                        env.DESCRIPTION = "Comparing Coverage Results"
                        updateCommitStatus(RX_DIR, COMMIT_INPROGRESS_STATUS, env.DESCRIPTION, ACCESS_TOKEN, GIT_COMMIT, BUILD_URL, CONTEXT_BUILD)
                        echo "---------------------- ${env.DESCRIPTION} ----------------------"
                        def branchCurrent = URLEncoder.encode(GIT_BRANCH, 'UTF-8')
                        def branchCompare = 'main'
                        echo "-------------------------- Comparing Coverage with ${branchCompare} Branch --------------------------"

                        def rootDir = pwd()
                        def sonarUtils = load "${rootDir}/pipelines/run-tests/utils/sonarUtils.groovy"

                        // Only check commit on PR branches
                        def checkCommitCurrent = GIT_BRANCH.startsWith('feature/') || GIT_BRANCH.startsWith('hotfix/') || GIT_BRANCH.startsWith('epic/')
                        echo "Check commit for current branch (${GIT_BRANCH}): ${checkCommitCurrent}"
                        def coverageCurrent = sonarUtils.getCoverageWithRetry(
                            GIT_BRANCH,
                            checkCommitCurrent,
                            env.PROJECT_KEY,
                            SONAR_TOKEN,
                            SONAR_SERVER,
                            GIT_COMMIT
                        )
                        def coverageOriginBranch = sonarUtils.getCoverageWithRetry(
                            branchCompare,
                            false,
                            env.PROJECT_KEY,
                            SONAR_TOKEN,
                            SONAR_SERVER,
                            null
                        )

                        echo "Current branch (${env.GIT_BRANCH}) coverage: ${coverageCurrent}%"
                        echo "${branchCompare} branch coverage: ${coverageOriginBranch}%"
                        if (coverageCurrent < coverageOriginBranch) {
                            env.ERROR_MESSAGE = "Coverage (${coverageCurrent}%) is lower than ${branchCompare} branch (${coverageOriginBranch}%)"
                            echo "-------------------------- ${env.ERROR_MESSAGE} --------------------------"
                            currentBuild.result = UNSTABLE
                            env.COMPARE_COVERAGE_STATUS = FAILED
                            unstable(env.ERROR_MESSAGE)
                        } else {
                            echo '-------------------------- Coverage is OK --------------------------'
                            currentBuild.result = SUCCESS
                        }
                    } catch (Exception e) {
                        env.ERROR_MESSAGE = "Comparing Coverage Results Failed"
                        echo "-------------------------- ${env.ERROR_MESSAGE} --------------------------"
                        echo "Exception occurred: " + e.toString()
                        currentBuild.result = UNSTABLE
                        unstable(env.ERROR_MESSAGE)
                    }
                }
            }
        }
    }
    post { // MARK: Post Actions
        failure {
            script {
                updateCommitStatus(RX_DIR, COMMIT_FAILED_STATUS, env.ERROR_MESSAGE, ACCESS_TOKEN, GIT_COMMIT, BUILD_URL, CONTEXT_BUILD)
                echo "---------------------- ${env.ERROR_MESSAGE} ----------------------"
            }
            cleanWs deleteDirs: true
            mail to: EMAIL_ADDRESS,
            subject: "⛔ ERROR - ${currentBuild.fullDisplayName}",
            mimeType: "text/html",
            body:  """
                <html>
                    <head>
                        <style>
                            body { font-family: 'Arial', sans-serif; }
                            .header { font-size: 16px; font-weight: bold; color: #FF0000; }
                        </style>
                    </head>
                    <body>
                        <p>__________________________________________________________</p>

                        <h2 class="header">🚫 ERROR 🚫</h2>

                        <p><strong>Reasons ⇢ <em>${env.ERROR_MESSAGE}</em></strong></p>

                        ${COMMIT_INFO}

                        <p>The build has failed unexpectedly. This failure isn't likely to be caused by failing tests.<br>💡 This build was on an Etendo RX environment.<br>To more information on the failing run visit: ${env.BUILD_URL}</p>

                        <p class="footer"><em>Best regards,<br>#EtendoBot 🤖</em></p>
                        <p>__________________________________________________________</p>
                    </body>
                </html>
            """
        }
        unstable {
            script {
                def mailSubject = ""
                def moreInfo = ""
                def bodyMessageError = ""

                if (env.TEST_STATUS == UNSTABLE) {
                    mailSubject = "Failed Tests"
                    if (env.FAILED_SUITES && !env.FAILED_SUITES.isEmpty()) {
                        bodyMessageError = "Failed Test Suites: ${env.FAILED_SUITES}"
                    } else {
                        bodyMessageError = "Failed tests have been detected in the RX Project."
                    }
                } else if (env.COMPARE_COVERAGE_STATUS == FAILED) {
                    mailSubject = "Coverage Decreased"
                    bodyMessageError = env.ERROR_MESSAGE
                    moreInfo = "Check the <a href='${env.PROJECT_URL}'>SonarQube Report</a> for more details about the coverage.<br/>"
                }
                env.EMAIL_SUBJECT = mailSubject
                env.MORE_INFO = moreInfo
                env.BODY_MESSAGE_ERROR = bodyMessageError

                updateCommitStatus(RX_DIR, COMMIT_FAILED_STATUS, env.EMAIL_SUBJECT, ACCESS_TOKEN, GIT_COMMIT, BUILD_URL, CONTEXT_BUILD)
                echo "---------------------- ${env.EMAIL_SUBJECT} ----------------------"
            }
            cleanWs deleteDirs: true
            mail to: EMAIL_ADDRESS,
            subject: "⚠️ ${env.EMAIL_SUBJECT} - ${currentBuild.fullDisplayName}",
            mimeType: "text/html",
            body:  """
                <html>
                    <head>
                        <style>
                            body { font-family: 'Arial', sans-serif; }
                            .header { font-size: 16px; font-weight: bold; color: #FFA500; }
                        </style>
                    </head>
                    <body>
                        <p>__________________________________________________________</p>

                        <h2 class="header">⚠️ ${env.EMAIL_SUBJECT} ⚠️</h2>
                        
                        <p><strong>Reasons ⇢ <em>${env.BODY_MESSAGE_ERROR}</em></strong></p>

                        ${COMMIT_INFO}

                        <p>
                            ${env.MORE_INFO}
                            To more information on the failing run, visit <a href='${env.BUILD_URL}'>Jenkins Build</a>
                        </p>
                        <p class="footer"><em>Best regards,<br>#EtendoBot 🤖</em></p>
                        <p>__________________________________________________________</p>
                    </body>
                </html>
            """
        }
        success {
            script {
                env.DESCRIPTION = "Successful Test Suites"
                updateCommitStatus(RX_DIR, COMMIT_SUCCESS_STATUS, env.DESCRIPTION, ACCESS_TOKEN, GIT_COMMIT, BUILD_URL, CONTEXT_BUILD)
                echo "---------------------- ${env.DESCRIPTION} ----------------------"
            }
            cleanWs deleteDirs: true
        }
    }
}
