FROM mcr.microsoft.com/openjdk/jdk:17-ubuntu AS config
ARG RX_VERSION
ENV RX_VERSION=${RX_VERSION}
COPY modules_core/com.etendorx.configserver/build/libs/com.etendorx.configserver-${RX_VERSION}.jar /opt/app/lib/com.etendorx.config.jar
ENTRYPOINT ["java", "-Dfile.encoding=UTF-8" , "-Dloader.path=./lib/" , "-jar", "/opt/app/lib/com.etendorx.config.jar"]

