FROM mcr.microsoft.com/openjdk/jdk:17-ubuntu AS edge
ARG RX_VERSION
ENV RX_VERSION=${RX_VERSION}
ENV SPRING_CONFIG_SERVER=http://config:8888
RUN useradd -m -s /bin/bash etendo && \
    mkdir -p /opt/app/lib && \
    chown -R etendo:etendo /opt/app
COPY modules_core/com.etendorx.edge/build/libs/com.etendorx.edge-${RX_VERSION}.jar /opt/app/lib/com.etendorx.edge.jar
USER etendo
ENTRYPOINT ["java", "-Dfile.encoding=UTF-8", "-Dloader.path=./lib/", "-jar", "/opt/app/lib/com.etendorx.edge.jar"]

