FROM mcr.microsoft.com/openjdk/jdk:17-ubuntu AS edge
ENV SPRING_CONFIG_SERVER=http://config:8888
COPY modules_core/com.etendorx.edge/build/libs/com.etendorx.edge-2.1.0.jar /opt/app/lib/com.etendorx.edge.jar
ENTRYPOINT ["java", "-Dfile.encoding=UTF-8" , "-Dloader.path=./lib/" , "-jar", "/opt/app/lib/com.etendorx.edge.jar"]