FROM mcr.microsoft.com/openjdk/jdk:17-ubuntu AS auth
ARG RX_VERSION
ENV RX_VERSION=${RX_VERSION}
COPY modules_core/com.etendorx.auth/build/libs/com.etendorx.auth-${RX_VERSION}.jar /opt/app/lib/com.etendorx.auth.jar
ENV CONFIG_SERVER_URL="http://classic:8080/etendo/buildConfig"
ENTRYPOINT ["java", "-Dfile.encoding=UTF-8" , "-Dloader.path=/opt/app/lib/" , "-jar", "/opt/app/lib/com.etendorx.auth.jar"]
 
