apiVersion: v1
kind: Pod
metadata:
  name: jenkins-node-rx-snap-0
  namespace: jenkins2025
  labels:
    app.kubernetes.io/name: jenkins-node-rx-snap
spec:
  containers:
    - name: compiler
      image: etendo/compiler_jenkins:1.0.7
      ports:
        - name: ssh
          containerPort: 22
          protocol: TCP
        - name: visualvm
          containerPort: 8000
          protocol: TCP
      resources:
        requests:
          cpu: 3072m
          memory: 6000Mi
        limits:
          cpu: 3072m
          memory: 8000Mi
      volumeMounts:
        - name: rsa-keys
          mountPath: /root/.ssh/
      lifecycle:
        postStart:
          exec:
            command:
              - bash
              - '-lc'
              - |
                set -e
                (apt-get update -y || true)
                if ! command -v docker >/dev/null 2>&1; then
                  (apt-get install -y docker.io || echo "⚠️ Couldn't install docker")
                fi
                (apt-get install -y curl || echo "⚠️ Couldn't install curl")
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
    - name: postgres
      image: postgres:16
      workingDir: /home/jenkins
      env:
        - name: POSTGRES_PASSWORD
          value: syspass
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  volumes:
    - name: rsa-keys
      configMap:
        name: rsa-keys
        defaultMode: 384
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  securityContext:
    privileged: true
