pipeline {
  options { // MARK: Pipeline Options
      disableConcurrentBuilds()
  }

  environment { // MARK: Environment Variables
    CONTEXT_NAME        = 'etendo'
    BBDD_SID            = 'etendo'
    BBDD_PORT           = '5432'
    BBDD_SYSTEMUSER     = 'postgres'
    BBDD_SYSTEMPASS     = 'syspass'
    BBDD_USER           = 'tad'
    BBDD_PASSWORD       = 'tad'
    NEXUS_USER          = credentials('nexus-admin-user')
    NEXUS_PASSWORD      = credentials('nexus-admin-passwd')
    GITHUB_USER         = 'etendobot'
    GITHUB_TOKEN        = credentials('github-read-package-token')
    REPOSITORY_URL      = 'https://repo.futit.cloud/repository/etendo-snapshot-jars'
    EMAIL_ADDRESS       = credentials('email_builds')
    ETENDO_RX_URL       = 'https://github.com/etendosoftware/etendo_rx'
    ETENDO_BASE_URL     = 'https://github.com/etendosoftware/etendo_base'
    MODULE_RX_URL       = 'git@github.com:etendosoftware/com.etendoerp.etendorx.git'

    COMMIT_AUTHOR_NAME  = sh(returnStdout: true, script: "git log -1 --pretty=format:'%an'").trim()
    COMMIT_AUTHOR_EMAIL = sh(returnStdout: true, script: "git log -1 --pretty=format:'%ae'").trim()

    SUCCESS = 'SUCCESS'
    FAILED = 'FAILED'
    ABORTED = 'ABORTED'

    JAVA_HOME = '/usr/lib/jvm/java-17-openjdk-amd64'
    ETENDO_RX_FOLDER = 'etendo_rx'
  }

  agent { // MARK: Agent Definition
    kubernetes {
      inheritFrom 'jenkins-node-rx-snap'
      defaultContainer 'jnlp'
      yamlFile 'pipelines/run-tests/Agent.yaml'
        }
    }

  stages {
    stage('Check Pipeline Skip Condition') { // MARK: Check Pipeline Skip Condition
      when {
        expression {
          GIT_BRANCH == 'develop'
        }
      }
      steps {
        script {
          try {
            echo "--------------- Checking if pipeline should be skipped ---------------"
            def changedFiles = sh(
                script: "git diff --name-only HEAD~1 HEAD",
                returnStdout: true
            ).trim()
                
            echo "Files changed in last commit: ${changedFiles}"
            
            // Check if only JenkinsFileTestCompile was changed
            def filesList = changedFiles.split('\n')
            def onlyJenkinsfile = filesList.every { it.startsWith("pipelines/run-tests/") } && filesList.size() > 0

            if (onlyJenkinsfile) {
                echo "⏭️ Only pipelines/run-tests/ related files were changed. Skipping pipeline execution."
                env.DESCRIPTION = "Pipeline Skipped - Only pipelines/run-tests/ files changed"
                
                echo "✅ Pipeline execution aborted successfully. Commit marked as success."
                currentBuild.result = ABORTED
                return
            } else {
                echo "✅ Pipeline will continue - Changes detected in other files or multiple files changed."
                currentBuild.result = SUCCESS
            }
          } catch (Exception e) {
            echo "❌ Error in pipeline skip condition check: ${e.getMessage()}"            
            env.DESCRIPTION = "Pipeline Check Failed"
            currentBuild.result = FAILED
            error("Failed to check pipeline skip condition: ${e.getMessage()}")
          }
        }
      }
    }

    stage ('Build Environment Etendo Classic') { // MARK: Build Etendo Classic
      when {
        expression {
          GIT_BRANCH == 'develop'
        }
      }
      steps {
        container('compiler') {
          script {
            try {
              echo '-------------- Building Classic Environment --------------'
              sh """
              git clone --branch develop ${ETENDO_BASE_URL} etendo_core
              """

              echo '-------------- Prepare gradle.properties --------------'
              sh """
              cd etendo_core
              echo \"
              context.name=${CONTEXT_NAME}
              bbdd.sid=${BBDD_SID}
              bbdd.port=${BBDD_PORT}
              bbdd.systemUser=${BBDD_SYSTEMUSER}
              bbdd.systemPassword=${BBDD_SYSTEMPASS}
              bbdd.user=${BBDD_USER}
              bbdd.password=${BBDD_PASSWORD}
              nexusUser=${NEXUS_USER}
              nexusPassword=${NEXUS_PASSWORD}
              githubUser=${GITHUB_USER}
              githubToken=${GITHUB_TOKEN}
              allow.root=true
              org.gradle.jvmargs=-Dfile.encoding=UTF-8\" > gradle.properties
              export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
              """

              echo '-------------- Clone modules of Classic --------------'
              withCredentials([sshUserPrivateKey(credentialsId: 'my-credentials', keyFileVariable: 'keyfile')]) {
                sh """
                cd etendo_core
                mkdir -p modules
                cd modules
                GIT_SSH_COMMAND=\"ssh -i ${keyfile} -o \"UserKnownHostsFile=/dev/null\" -o \"StrictHostKeyChecking=no\"\" git clone --branch ${GIT_BRANCH} ${MODULE_RX_URL}
                """
              }

              def buildGradleContent = """
                dependencies {
                    implementation(\"com.etendoerp.platform:etendo-core:latest.release\")
                }
              """

              echo '-------------- Compile Classic --------------'
              sh """
              cd etendo_core
              echo '${buildGradleContent}' >> build.gradle
              cat build.gradle
              ./gradlew clean --info
              ./gradlew prepareConfig --info
              ./gradlew setup --info
              ./gradlew install --info
              """

              echo '-------------- Build Classic Environment Succesful --------------'
              currentBuild.result = SUCCESS
            } catch (Exception e) {
              echo '-------------- Build Classic Environment Failed --------------'
              echo "Exception occurred: " + e.toString()
              currentBuild.result = FAILED
              error('Build Classic Failed')
            }
          }
        }
      }
    }

    stage ('Build Environment Etendo RX') { // MARK: Build Etendo RX
      when {
        allOf {
          expression {
            currentBuild.result == SUCCESS && GIT_BRANCH == 'develop'
          }
        }
      }
      steps {
        container('compiler') {
          script {
            try {
              echo '-------------- Building RX Environment --------------'
              sh """
              git clone --branch ${BRANCH_NAME} ${ETENDO_RX_URL}
              """

              echo '-------------- Prepare gradle.properties --------------'
              sh """
              cd ${ETENDO_RX_FOLDER}
              echo -e \"
              repositoryUser=${NEXUS_USER}
              repositoryPassword=${NEXUS_PASSWORD}
              repositoryUrl=${REPOSITORY_URL}
              githubUser=${GITHUB_USER}
              githubToken=${GITHUB_TOKEN}
              org.gradle.parallel=true
              org.gradle.daemon=false
              dasPushImage=
              authPushImage=
              edgePushImage=
              zapierIntegrationPushImage=
              asyncPushImage=
              pushUrl=
              pushUsername=
              pushPassword=
              bbdd.rdbms=POSTGRE
              bbdd.driver=org.postgresql.Driver
              bbdd.url=jdbc:postgresql://localhost:${BBDD_PORT}
              bbdd.sid=${BBDD_SID}
              bbdd.systemUser=${BBDD_SYSTEMUSER}
              bbdd.systemPassword=${BBDD_SYSTEMPASS}
              bbdd.user=${BBDD_USER}
              bbdd.password=${BBDD_PASSWORD}
              bbdd.sessionConfig=select update_dateFormat('DD-MM-YYYY')
              rx.generateCode=true
              rx.computedColumns=true
              rx.views=true
              exclude.entities.jar=true
              \" > gradle.properties
              export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
              """

              echo '-------------- Change version to Snapshot --------------'
              sh """
              cd ${ETENDO_RX_FOLDER}
              sed -i \"s/gradle.ext.version = \\(.*\\)\'/gradle.ext.version = \\1-SNAPSHOT\'/g\" settings.gradle
              """

              echo '-------------- Generate Entities --------------'
              sh """
              cd ${ETENDO_RX_FOLDER}
              ./gradlew generate.entities --info
              """

              echo '-------------- Build RX Environment Succesful --------------'
              currentBuild.result = SUCCESS
            } catch (Exception e) {
              echo '-------------- Build RX Environment Failed --------------'
              echo "Exception occurred: " + e.toString()
              currentBuild.result = FAILED
              error('Build RX Failed')
            }
          }
        }
      }
    }

    stage ("Publish JARs") { // MARK: Publish JARs
      when {
        allOf {
           expression {
            currentBuild.result == SUCCESS && GIT_BRANCH == 'develop'
          }
        }
      }
      steps {
        container('compiler') {
          script {
            try {
              echo '-------------- Publishing Snapshot JARs --------------'
              sh """
              export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
              cd ${ETENDO_RX_FOLDER}
              ./gradlew publish --info
              """
              echo '-------------- Snapshot JARs Published --------------'
              currentBuild.result = SUCCESS
            } catch (Exception e) {
              echo '-------------- Publication of Snapshot JARs Failed --------------'
              echo "Exception occurred: " + e.toString()
              currentBuild.result = FAILED
            }
          }
        }
      }
    }
  }

  post { // MARK: Post Actions
    fixed {
      mail to: EMAIL_ADDRESS,
      subject: "✅ FIXED - ${currentBuild.fullDisplayName}",
      body: """
${new Date()}
__________________________________________________________

✅ ERRORS FIXED ✅

Commit: ${ETENDO_RX_URL}/commit/${env.GIT_COMMIT}
Author: ${COMMIT_AUTHOR_NAME} <${COMMIT_AUTHOR_EMAIL}>

The problems found in the previous run/s have been fixed! 💪
Check out the output in the following link:
${env.BUILD_URL}
__________________________________________________________
        """
    }
    failure {
      cleanWs deleteDirs: true
      mail to: EMAIL_ADDRESS,
      subject: "⛔ ERROR - ${currentBuild.fullDisplayName}",
      body:  """
${new Date()}
__________________________________________________________

⛔ ERROR ⛔

Commit: ${ETENDO_RX_URL}/commit/${env.GIT_COMMIT}
Author: ${COMMIT_AUTHOR_NAME} <${COMMIT_AUTHOR_EMAIL}>

The build or publication has failed unexpectedly.
💡 This build was on an Etendo Environment.
To more information on the failing run visit:
${env.BUILD_URL}
__________________________________________________________
      """
    }
  }
}
