server.port=8092
spring.datasource.url=jdbc:postgresql://localhost:5432/etendo
spring.datasource.username=tad
spring.datasource.password=tad
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
scan.basePackage=com.etendorx.integration.to_openbravo.mapping
post-upsert=true

# Disable auth for local development
auth.disabled=true

# Expose actuator metrics
management.endpoints.web.exposure.include=health,metrics
