name: Check Docker Image Existence

on:
  create:
    branches:
      - 'feature/*'

jobs:
  check-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Check image and tag if not exist
        run: |
          echo "Checking existence of Docker image..."
          BRANCH_NAME=${{ github.ref_name }}
          BRANCH_NAME=$(echo $BRANCH_NAME | tr '/' '-')
          IMAGE_NAME="etendo/etendodata:rx-$BRANCH_NAME"
          if ! docker pull $IMAGE_NAME; then
            echo "Image doesn't exist. Tagging image from develop branch..."
            docker pull etendo/etendodata:rx-develop
            docker tag etendo/etendodata:rx-develop $IMAGE_NAME
            docker push $IMAGE_NAME
            echo "New image tagged and pushed: $IMAGE_NAME"
          else
            echo "Image exists: $IMAGE_NAME"
          fi
