name: Docker Build and Push

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'

env:
  VERSION: 1.0.1  # Definí la versión como variable global

jobs:
  build_and_push_dynamic_das:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push multi-arch image for dynamic-das
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t etendo/dynamic-das:${{ env.VERSION }} --push -f resources/dynamic-das/Dockerfile .

  build_and_push_dynamic_gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push multi-arch image for dynamic-gradle
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t etendo/dynamic-gradle:${{ env.VERSION }} --push -f resources/dynamic-gradle/Dockerfile .
