name: Docker Build and Push

on:
  push:
    branches:
      - feature/ERP-774

jobs:
  build_and_push_dynamic_das:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build amd64 image for dynamic-das
        run: |
          export VERSION=1.0.1
          docker buildx build --platform linux/amd64 -t etendo/dynamic-das:${VERSION}-amd64 -f resources/dynamic-das/Dockerfile --push .

      - name: Build arm64 image for dynamic-das
        run: |
          export VERSION=1.0.1
          docker buildx build --platform linux/arm64 -t etendo/dynamic-das:${VERSION}-arm64 -f resources/dynamic-das/Dockerfile --push .

  build_and_push_dynamic_gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build amd64 image for dynamic-gradle
        run: |
          export VERSION=1.0.1
          docker buildx build --platform linux/amd64 -t etendo/dynamic-gradle:${VERSION}-amd64 -f resources/dynamic-gradle/Dockerfile --push .

      - name: Build arm64 image for dynamic-gradle
        run: |
          export VERSION=1.0.1
          docker buildx build --platform linux/arm64 -t etendo/dynamic-gradle:${VERSION}-arm64 -f resources/dynamic-gradle/Dockerfile --push .

  create_and_push_manifest_dynamic_das:
    runs-on: ubuntu-latest
    needs: build_and_push_dynamic_das
    steps:
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Create and Push Docker Manifest for dynamic-das
        run: |
          export VERSION=1.0.1
          docker manifest create etendo/dynamic-das:${VERSION} \
            etendo/dynamic-das:${VERSION}-amd64 \
            etendo/dynamic-das:${VERSION}-arm64
          docker manifest annotate etendo/dynamic-das:${VERSION} etendo/dynamic-das:${VERSION}-amd64 --os linux --arch amd64
          docker manifest annotate etendo/dynamic-das:${VERSION} etendo/dynamic-das:${VERSION}-arm64 --os linux --arch arm64
          docker manifest push etendo/dynamic-das:${VERSION}

  create_and_push_manifest_dynamic_gradle:
    runs-on: ubuntu-latest
    needs: build_and_push_dynamic_gradle
    steps:
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Create and Push Docker Manifest for dynamic-gradle
        run: |
          export VERSION=1.0.1
          docker manifest create etendo/dynamic-gradle:${VERSION} \
            etendo/dynamic-gradle:${VERSION}-amd64 \
            etendo/dynamic-gradle:${VERSION}-arm64
          docker manifest annotate etendo/dynamic-gradle:${VERSION} etendo/dynamic-gradle:${VERSION}-amd64 --os linux --arch amd64
          docker manifest annotate etendo/dynamic-gradle:${VERSION} etendo/dynamic-gradle:${VERSION}-arm64 --os linux --arch arm64
          docker manifest push etendo/dynamic-gradle:${VERSION}
